-- CREATE DATABASE contabilidad

-- USE contabilidad

-- SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
-- START TRANSACTION;  
-- SET time_zone = "+00:00";

--
-- Creacion de la Tabla
--

CREATE TABLE `persona` (
    id_p INT NOT NULL AUTO_INCREMENT,
    codMod VARCHAR(10) NOT NULL,
    nombres VARCHAR(100) NOT NULL,
    condicion VARCHAR(20) NOT NULL,
    -- PRIMARY AND FOREING KEY ---
    PRIMARY KEY (id_p)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

CREATE TABLE `boleta` (
    n INT NOT NULL AUTO_INCREMENT,
    fecha VARCHAR(30) NOT NULL,
    codPlanilla VARCHAR(15) NOT NULL,
    anulado VARCHAR(5) NOT NULL,
    doc VARCHAR(50) NOT NULL,
    id_p INT NOT NULL,
    -- PRIMARY AND FOREIGN KEY --
    PRIMARY KEY (n),
    FOREIGN KEY (id_p) REFERENCES `persona`(id_p)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

CREATE TABLE `monto` (
    id_m INT NOT NULL AUTO_INCREMENT,
    cod INT NOT NULL,
    monto FLOAT NOT NULL,
    n INT NOT NULL,
    -- PRIMARY AND FOREIGN KEY --
    PRIMARY KEY (id_m),
    FOREIGN KEY (n) REFERENCES `boleta`(n)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

CREATE TABLE `codigo` (
    id_c INT NOT NULL AUTO_INCREMENT,
    cod INT NOT NULL,
    nombre VARCHAR(25) NOT NULL,
    doc VARCHAR(50) NOT NULL,
    -- PRIMARY AND FOREIGN KEY --
    PRIMARY KEY (id_c)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

CREATE TABLE `codigo_aux` (
    id_ca INT NOT NULL AUTO_INCREMENT,
    nombre VARCHAR(25) NOT NULL,
    id_c INT NOT NULL,
    -- PRIMARY AND FOREIGN KEY --
    PRIMARY KEY (id_ca),
    FOREIGN KEY (id_c) REFERENCES `codigo`(id_c)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;
